### PR TITLE
[DNM] 3.0.0 release

### PR DESCRIPTION
**Pull request by JeroenDeDauw**

### CODE REVIEW

**Comment by JeroenDeDauw** [comment]
Oops... https://github.com/wmde/Diff/pull/77 still is not merged

**Comment by thiemowmde** [comment]
-2 until the issue related to the self-merge on #74 is resolved. Pinging @tobijat.

**Comment by JeroenDeDauw** [comment]
What exactly do you want to resolve and how? Do you want us to build a time machine so we can prevent that merge from having happened? Do you want a written letter of apology directed at you?

I'm not seeing any concrete problem here, beyond what strikes me as a significant waste of department resources by creating a fuss. I think we all have more important things to be doing.

**Comment by manicki** [comment]
The concrete problem I can see is the fact that Wikibase is not going to be able to use Diff >= 3.0.0 as long as it is PHP < 7 compatible, which, like it or not, is going to last for a while.
I believe we could try focusing on this than on the fact of self merging some PR, and making the whole thing some kind of personal issue.

**Comment by JeroenDeDauw** [comment]
> The concrete problem I can see is the fact that Wikibase is not going to be able to use Diff >= 3.0.0 as long as it is PHP < 7 compatible, which, like it or not, is going to last for a while.

While that is true, it is in itself not a problem. I can think of some theoretical (but in this case rather unlikely) situations to arise that might require someone to spend an extra half minute or maybe even a few minutes. That does not stike me as a problem either though. And if it is, then focusing on this problem is a way bigger problem than the problem itself. And if there is a real problem caused by the above, I do wonder why it has not been outlined. @thiemowmde can you please do that? I'm very unhappy that I am forced to spend my time on this in order to move things forewards.

**Pull request closed without merging**
