### PR TITLE
Remove MediaWiki registration and release 2.2

### PR DESCRIPTION
**Pull request by legoktm**
@addshore

### CODE REVIEW

**Comment by JeroenDeDauw** [comment]
This is cool and all but I am worried that the branch `21x` will be interpreted by composer as version 21. Normally the name would be `2.1.x`

**Comment by JeroenDeDauw** [comment]
It won't be listed as a version there I think.

But do try

   composer require diff/diff 21

or 

    composer require diff/diff *

I'm not on a dev box myself ATM. I've seen purely numerical branch names cause this problem. Though this was over a year ago, so things might have changed. And perhaps the x at the end of the name prevents the problem.

**Comment by legoktm** [comment]
```
km@km-tp ~/p/sandbox> composer require diff/diff 21
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package diff/diff 21 exists as diff/diff[0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0, 1.0.1, 2.0.0, 2.1.0, 2.2.0, 3.0.0, dev-21x, dev-composerMd, dev-listChange, dev-listDiffer, dev-master, 3.0.x-dev, dev-upperbound] but these are rejected by your constraint.
km@km-tp ~/p/sandbox> composer require diff/diff \*
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
  - Installing diff/diff (3.0.0): Downloading (100%)         
Writing lock file
Generating autoload files
```

**Comment by JeroenDeDauw** [comment]
Great. Thanks for checking!

**Comment by JeroenDeDauw** [comment]
I realized that this is still off though. Either this branch is meant to be temporary and can be deleted or it is meant to stay and should have a name reflecting what it is: a 2.x branch. I've thus renamed it as it is not a 2.1.x branch. The composer branch alias is also wrong now, fixed with https://github.com/wmde/Diff/pull/85

**Pull request merged**
